version 0.1.3 fix install package

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,26 +1,32 @@
 #!/bin/sh
 
-echo "Sourcing debconf Library"
+# don't put anything before here or it will break debconf!
+# Source debconf library.
 set -e
 . /usr/share/debconf/confmodule
  
 # Fetching configuration from debconf
 # for answer to startup program
 db_get roboticscape/question1
+PROG=$RET
 
-echo "user selected $RET"
+echo "user selected $PROG"
 
-if [ "$RET" = "blink" ]; then
-	ln -s -f /usr/bin/blink /etc/roboticscape/link_to_startup_program
-elif  [ "$RET" = "balance" ]; then
-	ln -s -f /usr/bin/balance /etc/roboticscape/link_to_startup_program
-elif  [ "$RET" = "none" ]; then
-	ln -s -f /usr/bin/bare_minimum /etc/roboticscape/link_to_startup_program
-else
-	echo "invalid answer to startup program question"
-	exit 1
+if [ ! -d "/etc/roboticscape" ]; then
+  echo "making /etc/roboticscape"
+  mkdir /etc/roboticscape
 fi
 
+if [ "$PROG" = "blink" ]; then
+	ln -s -f /usr/bin/blink /etc/roboticscape/link_to_startup_program
+elif  [ "$PROG" = "balance" ]; then
+	ln -s -f /usr/bin/balance /etc/roboticscape/link_to_startup_program
+elif  [ "$PROG" = "none" ]; then
+	ln -s -f /usr/bin/bare_minimum /etc/roboticscape/link_to_startup_program
+else
+	echo "invalid answer to question"
+	exit 1
+fi
 
 # ld config to make sure libroboticscape.so is recognized
 echo "running ldconfig"
