package fiddling

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,7 +1,29 @@
 #!/bin/sh
 
+echo "Sourcing debconf Library"
+set -e
+. /usr/share/debconf/confmodule
+ 
+# Fetching configuration from debconf
+# for answer to startup program
+db_get roboticscape/question1
+
+echo "user selected $RET"
+
+if [ "$RET" = "blink" ]; then
+	ln -s -f /usr/bin/blink /etc/roboticscape/link_to_startup_program
+elif  [ "$RET" = "balance" ]; then
+	ln -s -f /usr/bin/balance /etc/roboticscape/link_to_startup_program
+elif  [ "$RET" = "none" ]; then
+	ln -s -f /usr/bin/bare_minimum /etc/roboticscape/link_to_startup_program
+else
+	echo "invalid answer to startup program question"
+	exit 1
+fi
+
 
 # ld config to make sure libroboticscape.so is recognized
+echo "running ldconfig"
 ldconfig
 
 # enable services
@@ -13,27 +35,6 @@ echo "Starting battery_monitor Service"
 systemctl start battery_monitor
 echo "Enabling roboticscape Service"
 systemctl enable roboticscape
-
-
-# startup program question
-echo "Sourcing debconf Library"
-set -e
-. /usr/share/debconf/confmodule
-
-echo "Getting roboticscape/question1"
-db_get roboticscape/question1
-PROG=$RET
-
-echo "user selected $PROG"
-
-if [ "$PROG" = "blink" ]; then
-	ln -s -f /usr/bin/blink /etc/roboticscape/link_to_startup_program
-elif  [ "$PROG" = "balance" ]; then
-	ln -s -f /usr/bin/balance /etc/roboticscape/link_to_startup_program
-elif  [ "$PROG" = "none" ]; then
-	ln -s -f /usr/bin/bare_minimum /etc/roboticscape/link_to_startup_program
-fi
-
 
 echo "Configuring Device Tree"
 configure_robotics_dt.sh
